export const QueryKeys = {
  STUDENTS: "STUDENTS",
  COURSE: "COURSE",
  LECTURE: "LECTURE",
  MATERIAL: "MATERIAL",
  ASSIGNMENT: "ASSIGNMENT",
  SUBMISSION: "SUBMISSION",
  GRADE: "GRADE",
  REPORT: "REPORT",
  LOG: "LOG",
  PAYMENT: "PAYMENT",
  USER_BY_EMAIL: (email) => "USER_" + email,
};
